saidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('saidia_app.urls'))
]

saidia_app/urls.py
from django.urls import path

from . import views

app_name = "saidia_app"

urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login, name = "login"),
    path("mn", views.manage, name = "manage"),
    path("mn/add", views.add_orphanage, name = "add_orphanage"),
    path("op/<str:orph_id>", views.orphanage, name = "orphanage"),
    path("ad/nd/<str:oph>", views.add_need, name = "add_need"),
    path("rm/nd/<str:orph_id>/<str:need_id>", views.remove_need, name = "remove_need"),
    path("rm/op/<int:orph_id>", views.remove_orphanage, name="remove_orphanage"),
    path("register", views.register, name="register"),
    path("get_coord", views.get_coord, name="get_coord"),
    path("logout", views.logout, name="logout"),
    path("error/<str:error_id>", views.error, name="error")
]

saidia_app/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 40)
    x_coordinate = models.DecimalField(max_digits=23, decimal_places=20)
    y_coordinate = models.DecimalField(max_digits=23, decimal_places=20)

    def __str__(self):
        return f"{self.id},{self.name}"

class Needs(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 40)

    def __str__(self):
        return f"{self.name}"

class User(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 150)
    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['email'], name="unique_user")
        ]

    def __str__(self):
        return f"{self.id},{self.first_name},{self.last_name},{self.email},{self.datetime}"

class Manager(models.Model):
    user =  models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    password = models.CharField(max_length =  200)

    def __str__(self):
        return f"{self.user}"

class Orphanage(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 40)
    manager = models.ForeignKey(Manager, on_delete = models.CASCADE)
    needs = models.ManyToManyField(Needs)
    capacity = models.IntegerField()
    location = models.ForeignKey(Location, on_delete = models.CASCADE)
    x_coordinate = models.DecimalField(max_digits=23, decimal_places=20)
    y_coordinate = models.DecimalField(max_digits=23, decimal_places=20)
    datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

class Review(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orphanage = models.ForeignKey(Orphanage, on_delete=models.CASCADE)
    message = models.CharField(max_length=200)
    datetime = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"{self.user},{self.orphanage},{self.message},{self.datetime}"

saidia_app/forms.py
from django.forms import ModelForm
from django import forms

from saidia_app.models import *

# make you forms here

class LoginForm(forms.Form):
    email = forms.EmailField()

class RegisterForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class AuthForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)


class OrphanageForm(ModelForm):
    class Meta:
        model = Orphanage
        fields = ['name','capacity','location', 'x_coordinate', 'y_coordinate']

class OphNeedsForm(ModelForm):
    class Meta:
        model = Orphanage
        fields = ['needs']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['message']

saidia_app/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect

from saidia_app.forms import *
from saidia_app.models import *
from saidia_app.cipher import *
from saidia_app.error_list import *

# Create your views here.

def add_orphanage(request):
    # one can only access this view if they have logged in
    # otherwiser an error status with the 404 code will be raised
    if "user" in request.session:
        user_id = request.session["user"]

        # checks if manager is adding a new orphanage
        if request.method == "POST":
            # TODO: ADD CODE TO ADD NEW ORPHANAGE TO THE SYSTEM
            user = User.objects.get(id = user_id)
            manager = Manager.objects.get(user = user)

            # extract data from orphanage_form
            orphanage_form = OrphanageForm(request.POST)
            if orphanage_form.is_valid():
                # get orphanage name
                orph_name = orphanage_form.cleaned_data['name']
                # get capacity
                orph_cap = orphanage_form.cleaned_data['capacity']
                # get location
                orph_loc = orphanage_form.cleaned_data['location']
                # get x-coordinate and y_coordinate
                x_coord = orphanage_form.cleaned_data['x_coordinate']
                y_coord = orphanage_form.cleaned_data['y_coordinate']

                # create model object and save it
                orphanage = Orphanage(
                    name = orph_name,
                    manager = manager,
                    capacity = orph_cap,
                    location = orph_loc,
                    x_coordinate = x_coord,
                    y_coordinate = y_coord
                )
                orphanage.save()
            return redirect('saidia_app:manage')
        else:
            orphanage_form = OrphanageForm()
            return render(request, 'saidia_app/add_orphanage.html',{
                "orphanage_form": orphanage_form,
            })
    return redirect("saidia_app:error", 400)

def add_need(request, oph):
    # one can only add need if they
    # are logged in.
    # otherwise, error is returned
    if 'user' in request.session:
        if request.method == "POST":
            oph_need_form = OphNeedsForm(request.POST)
            # validate form data
            if oph_need_form.is_valid():
                orphanage = Orphanage.objects.get(id = oph) #get orphanage with specified id
                need = oph_need_form.cleaned_data["needs"][0]
                orphanage.needs.add(need.id)
                return redirect("saidia_app:add_need",oph)

        # perform in GET method
        oph_need_form = OphNeedsForm()
        needs = Orphanage.objects.get(id = oph).needs.all()

        return render(request, "saidia_app/add_need.html", {
            "oph_need_form": oph_need_form,
            "orph_id":oph,
            "orph_needs": needs
        })
    else:
        return redirect("saidia_app:error", 400)

def error(request, error_id):
    message = errors.get_error(error_id)

    return render(request, "saidia_app/error.html", {
        "message": message
    })

def get_coord(request):
    # get location id
    if request.method == "POST":
        location_id = request.POST['id']
        location = Location.objects.get(id = location_id)
        print(location.x_coordinate)

    body = {
        "x": location.x_coordinate,
        "y": location.y_coordinate
    }
    data = {
        'head': 'locationCoordinates',
        'body': body
    }
    return JsonResponse(data)

def index(request):
    orphanages = Orphanage.objects.all()
    if request.method == "POST":
        if "orphanage" in request.POST:
            orphanages = Orphanage.objects.filter(name__icontains = request.POST["orphanage"])
            return render(request, "saidia_app/index.html",{
                "orphanages": orphanages
            })


         # coordinates of the donor
         # remember them for subsequent calls
        coordinates = {
            "lat": request.POST["lat"],
            "lng": request.POST["lon"]
        }
        request.session["coord"] = coordinates 

        # feedback to ajax request
        data = {
            'head': 'close_orphanages',
            'body': 'success'
        }
        return JsonResponse(data)

    return render(request, "saidia_app/index.html",{
        "orphanages": orphanages
    })

def login(request):
    if request.method == 'POST':
        user_form = LoginForm(request.POST)
        auth_form = AuthForm(request.POST)

        # validates form
        if user_form.is_valid() and auth_form.is_valid():
            email = user_form.cleaned_data['email']

            # get user with specified email
            # if exist, validate password otherwise return error
            user = User.objects.filter(email = email)
            if user.count() != 0:
                user = user[0]
                password = Manager.objects.filter(
                    user = user,
                    password = encrypt(auth_form.cleaned_data['password'])
                )

                # if a record with specified user and password returns
                # redirect to management page
                if password.count() != 0:
                    # create session for the user
                    request.session["user"] = user.id
                    return redirect('saidia_app:manage')

        # eror if invalid data
        error = "invalid credentials"

        return render(request, "saidia_app/login.html",{
            "user_form": user_form,
            "auth_form": auth_form,
            "error": error
        })
    else:
        user_form = LoginForm()
        auth_form = AuthForm()
        return render(request, "saidia_app/login.html",{
            "user_form": user_form,
            "auth_form": auth_form
        })

def logout(request):
    request.session.pop("user")
    return redirect("saidia_app:index")

def manage(request):
    if "user" in request.session:
        # get list of orphanages for the manager in session.
        user_id =  request.session["user"] #get user id from session
        user = User.objects.get(id = user_id) #get user with specified id
        manager = Manager.objects.get(user = user) #get the id of the manager
        orphanages = Orphanage.objects.filter(manager = manager) # get orphanages manaaged by this specific manager

        return render(request, "saidia_app/manage.html",{
            "manager": request.session["user"],
            "orphanages": orphanages
        })
    return redirect("saidia_app:error", 403)

def orphanage(request, orph_id):
    orphanage = Orphanage.objects.get(id = orph_id)

    # TODO: when method is POST
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            message = review_form.cleaned_data['message']
        else:
            # TODO: fix redirect
            return redirect("saidia_app:error", 404)
        if 'user' in request.session:
            user_id = request.session['user']

            # create and save review
            review  = Review(
                user = User.objects.get(id =user_id),
                orphanage = Orphanage.objects.get(id = orph_id),
                message = message
            )
            review.save()
        else:
            return redirect("saidia_app:error", 400)

    reviews = Review.objects.filter(orphanage = orph_id)
    review_form = ReviewForm()
    return render(request, "saidia_app/orphanage.html", {
        "orphanage": orphanage,
        "review_form": review_form,
        "reviews": reviews
    })

def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        auth_form = AuthForm(request.POST)

        # save user object if valid
        if user_form.is_valid():
            user = user_form.save()

            if auth_form.is_valid():
                # use user object to create Manager object
                # password is hashed first before encryption
                password = encrypt(auth_form.cleaned_data['password'])

                manager =  Manager(user = user, password=password)
                manager.save()

                #create session for the user
                request.session["user"] = user.id

                # Manager has successfully been created
                # redirect to the management page

                return redirect('saidia_app:manage')
    else:
        user_form = RegisterForm()
        auth_form = AuthForm()
    return render(request, "saidia_app/register.html",{
        "user_form": user_form,
        "auth_form": auth_form
    })

def remove_need(request, orph_id, need_id):
    # one can only remove need if
    # session is established
    if 'user' in request.session:
        user_id = request.session['user']

        # delete the need from the orphanage
        orphanage = Orphanage.objects.get(id = orph_id)
        need = Needs.objects.get(id = need_id)
        orphanage.needs.remove(need)
        return redirect("saidia_app:add_need",orph_id)

    return redirect("saidia_app:index")

def remove_orphanage(request, orph_id):
    if 'user' in request.session:
        user_id = request.session['user']

        # delete the orphanage
        Orphanage.objects.get(id = orph_id).delete()
    return redirect('saidia_app:manage')

saidia_app/templates/saidia_app/add_need.html
{% extends "saidia_app/manage_layout.html" %}

{% load static %}

{% block body %}
<div class="container">
  <div class="">
    {% if orph_needs %}
      {% for need in orph_needs %}
        <div class="nd_cntainer">
          <h3>{{need.name}}</h3>
          <a class="option" href="{% url 'saidia_app:remove_need' orph_id need.id %}">remove</a>
        </div>
      {% endfor %}
    {% else %}
      no needs currently
    {% endif %}
  </div>
  <form action="{%url 'saidia_app:add_need' orph_id %}" method="post">
    {% csrf_token %}
    {{oph_need_form}}
    <button type="submit" name="button">add</button>
  </form>
</div>
{% endblock %}

saidia_app/templates/saidia_app/add_orphanage.html
{% extends "saidia_app/manage_layout.html" %}

{% load static %}

{% block body %}
<div class="container">
  <form action="{% url 'saidia_app:add_orphanage' %}" method="post">
    {% csrf_token %}
    {{orphanage_form}}
    <button type="submit" name="button">add</button>
  </form>
  <div id="map">
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'saidia_app/scripts/add_orph_ui.js'%}" charset="utf-8"></script>
<script src="{% static 'saidia_app/scripts/ajax_rqst.js'%}" charset="utf-8"></script>
<script src="{% static 'saidia_app/scripts/location_coordinates.js'%}" charset="utf-8"></script>
<script type="text/javascript">initMap()</script>
{% endblock %}

saidia_app/templates/saidia_app/error.html
{% extends "saidia_app/user_layout.html" %}

{% block body %}
<div class="error-cont">
  {{message}}
</div>
<div class="error-alt-cont">
  return <a href="{% url 'saidia_app:index'%}">Home</a>
</div>
{% endblock %}

saidia_app/templates/saidia_app/form_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'saidia_app/styles/form_layout.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div id="FrmDv">
      <div class="TtlSct">
        <h3>{% block form_title %}{% endblock %}</h3>
      </div>
      <div class="FrmSct">
        {% block form %}{% endblock %}
      </div>
      <div class="FtrSct">
        {% block footer %}{% endblock %}
      </div>
    </div>
  </body>
</html>

saidia_app/templates/saidia_app/index.html
{% extends "saidia_app/user_layout.html" %}

{% load static %}

{% block body %}
  {% if orphanages %}
    {% for orphanage in orphanages %}
    <a class="container2" href = "{% url 'saidia_app:orphanage' orphanage.id %}">
      <h2>{{orphanage.name}}</h2>
      <h3>{{orphanage.location}}</h3>
      <h4>{{orphanage.capacity}} children</h4>
    </a>
    {% endfor %}
  {% else %}
    <p>there are no orphanages</p>
  {% endif %}

{% endblock %}

{% block scripts %}
<script src="{% static 'saidia_app/scripts/validation.js'%}" type="text/javascript"></script>
<script src="{% static 'saidia_app/scripts/ajax_rqst.js'%}" type="text/javascript"></script>
<script src="{% static 'saidia_app/scripts/get_user_location.js'%}" type="text/javascript"></script>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded',()=>{
    getPosition();
  });
</script>
{% endblock %}

saidia_app/templates/saidia_app/login.html
{% extends "saidia_app/form_layout.html" %}

{% block title %}
LOGIN
{% endblock %}

{% block form_title %}
LOGIN
{% endblock %}

{% block form %}
  <form class="" action="{% url 'saidia_app:login' %}" method="post">
    {% csrf_token %}
    {{user_form}}
    {{auth_form}}
    <button type="submit" name="submit">LOGIN</button>
  </form>

  {% if error %}
  <div class="ErrorDiv">
    {{error}}
  </div>
  {% endif %}

{% endblock %}

{% block footer %}
<p>are you a manager, <a href="{%url 'saidia_app:register'%}">register</a></p>
{% endblock %}

saidia_app/templates/saidia_app/main_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>saidia</title>
    <link rel="stylesheet" href="{% static 'saidia_app/styles/main_layout.css' %}">
    <link rel="stylesheet" href="{% static 'saidia_app/styles/home.css' %}">
    <link rel="stylesheet" href="{% static 'saidia_app/styles/orph_cntainer.css' %}">
    <link rel="stylesheet" href="{% static 'saidia_app/styles/conf.css' %}">
  </head>
  <body>
    {% csrf_token %}
    <div id="lft_div">
        <div class="app_ttl">
          <div class="app_logo">
            <img src="{% static 'saidia_app/icons/logo.png'%}" alt="saidia">
          </div>
          <div class="app_name">
            <h2>Saidia</h2>
          </div>
        </div>
        <div class="srch_sect">
          <form action="{% url 'saidia_app:index' %}" method="post">
            {% csrf_token %}
            <input type="text" name="orphanage" placeholder="search orphanage here">
            <button type="submit" name="submit">
              <img src="{%static 'saidia_app/icons/search.svg'%}" alt="">
            </button>
          </form>
        </div>

        <div class="main_optns">
            <div class="optn" style="top:0px;"></div>
            <a class="optn" href="{% url 'saidia_app:index'%}">
              <div>
                <img src="{%static 'saidia_app/icons/home.svg'%}" alt="home">
                <p>Home</p>
              </div>
            </a>
            <a class="optn" href="{% url 'saidia_app:manage'%}">
              <div>
                <img src="{%static 'saidia_app/icons/manage.png'%}" alt="manage">
                <p>Manage</p>
              </div>
            </a>
            {% if 'user' in request.session %}
            <a class="optn" href="{% url 'saidia_app:logout' %}">
              <div>
                <img src="{%static 'saidia_app/icons/register.png'%}" alt="register">
                <p>logout</p>
              </div>
            </a>
            {% else %}
            <a class="optn" href="{% url 'saidia_app:register' %}">
              <div>
                <img src="{%static 'saidia_app/icons/register.png'%}" alt="register">
                <p>Register</p>
              </div>
            </a>
            {% endif %}
        </div>
        <!-- <div class="footer">
          <a href="#">HELP</a>|
          <a href="#">ABOUT</a>|
          <a href="#">TERMS</a>|
        </div> -->
    </div>
    <div id="main_div">
      {% block body %}{% endblock %}
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7tw0O1sxW-bRcxovqKl_wMXN25_nrSlU"></script>
    <script src="{% static 'saidia_app/scripts/marker_coordinates.js'%}" charset="utf-8"></script>
    <script src="{% static 'saidia_app/scripts/main_ui.js'%}" type="text/javascript"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

saidia_app/templates/saidia_app/manage.html
{% extends "saidia_app/manage_layout.html" %}

{% block body %}
<div id="add_orph_cont">
  <a href="{% url 'saidia_app:add_orphanage'%}">add orphanage</a>
</div>

<h2>Orphanages</h2>

{% if orphanages %}
  {% for orphanage in orphanages %}
  <div class="orph_cont" data-id="{{orphanage.id}}">
    <h2>{{orphanage.name}}</h2>
    <h3>{{orphanage.location}}</h3>
    <a class="option" href="{% url 'saidia_app:add_need' orphanage.id %}">edit</a>
    <a class="option" href="{% url 'saidia_app:remove_orphanage' orphanage.id %}">remove</a>
  </div>
  {% endfor %}
{% else %}
  <h4>There are no orphanages you are currently managing</h4>
{% endif %}

{% endblock %}

saidia_app/templates/saidia_app/manage_layout.html
{% extends "saidia_app/main_layout.html" %}

{% block scripts %}
<script type="text/javascript">
  changeOptn(optnLst[2]);
</script>
{% endblock %}

saidia_app/templates/saidia_app/orphanage.html
{% extends "saidia_app/user_layout.html" %}

{% block body %}
<div class="container">
  <div class="container2">
    <h1>{{orphanage.name}}</h1>
    <h3>{{orphanage.location}}</h3>
    <h4>Capacity: {{orphanage.capacity}} children</h4>

    <h2 class="ttle">Needs</h2>
    <div class="NeedsContainer">
      {% if orphanage.needs.all %}
        {% for need in orphanage.needs.all %}
          <div class="need">{{need}}</div>
        {% endfor %}
      {% else %}
        <p>There are no needs specified</p>
      {% endif %}
    </div>

    <h2 class="ttle">reviews</h2>
    <!-- TODO: write code to list down avaialable reviews -->
    <div class="backg3">
    {% for review in reviews %}
      <div class="comment-cont">
        <p>{{review.message}}</p>
        <p>
          <span class="bold">by</span>
          <span>{{review.user.last_name}}</span>
          <span class="bold">on</span>
          <span>{{review.datetime}}</span>
        </p>
      </div>
    {% endfor %}
    </div>

    <form class="" action="{% url 'saidia_app:orphanage' orphanage.id %}" method="post">
      {% csrf_token %}
      {{review_form}}
      <button type="submit" name="button">submit</button>
    </form>
  </div>
  <div id="map">
  </div>
</div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    lat = {{orphanage.x_coordinate}}
    lng = {{orphanage.y_coordinate}}
    const myLatLng = {lat : lat, lng: lng}
    initMap(lat,lng)
    updateMarker(myLatLng)
  </script>
{% endblock %}

saidia_app/templates/saidia_app/register.html
{% extends "saidia_app/form_layout.html" %}

{% block title %}
REGISTER
{% endblock %}

{% block form_title %}
REGISTER
{% endblock %}

{% block form %}
  <form class="" action="{% url 'saidia_app:register' %}" method="post">
    {% csrf_token %}
    {{user_form}}
    {{auth_form}}
    <button type="submit" name="submit">REGISTER</button>
  </form>
{% endblock %}

{% block footer %}
<p>Already have an account, <a href="{%url 'saidia_app:login'%}">login</a></p>
{% endblock %}

saidia_app/templates/saidia_app/user_layout.html
{% extends "saidia_app/main_layout.html" %}

{% block scripts %}
<script type="text/javascript">
  changeOptn(optnLst[1]);
</script>
{% endblock %}